### ISSUE TITLE
some consistency

### ISSUE THREAD

**Issue by Symmettry** [FlorianMichael/DietrichEvents2#3]
I've noticed in most files you've used the `final` keyword everywhere possible, but in the BreakableEvent and CancellableEvent there are a few cases where `final` is not used

I'm unsure whether this is intentional or not but I would like to bring it to attention

**Comment by FlorianMichael** [comment]
They are missing final statements because those are just getters/setters generated by my IDE

**Comment by Symmettry** [comment]
ah makes sense

**Comment by FlorianMichael** [comment]
I don't know if I should change that in my codestyle, it helps to split between auto generated / common code and self written stuff, is there any argument for changing it? Those final statements doesn't do anything anyway, otherwise I would close this issue for now.

**Comment by Symmettry** [comment]
yeah it's only method parameters so it's little to no gain at all ever so you should be fine
